name: MkDocs Build

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install MkDocs
      run: |
        pip install mkdocs
        pip install mkdocs-material  # Add theme installation if needed

    - name: Build MkDocs Site
      run: mkdocs build

    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: ./site/api-docs
        spec-file: ./swagger/swagger.yaml
        # personal_token: ${{ secrets.PAT }}

    - name: Deploy Site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: ./site
