name: Generate API Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: ./api-docs
        spec-file: ./swagger/swagger.yaml
        # personal_token: ${{ secrets.PAT }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: ./site/swagger-ui
